// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: project.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_project_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_project_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_project_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_project_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_project_2eproto;
namespace project {
class Project;
struct ProjectDefaultTypeInternal;
extern ProjectDefaultTypeInternal _Project_default_instance_;
class ProjectHeader;
struct ProjectHeaderDefaultTypeInternal;
extern ProjectHeaderDefaultTypeInternal _ProjectHeader_default_instance_;
class ProjectNames;
struct ProjectNamesDefaultTypeInternal;
extern ProjectNamesDefaultTypeInternal _ProjectNames_default_instance_;
}  // namespace project
PROTOBUF_NAMESPACE_OPEN
template<> ::project::Project* Arena::CreateMaybeMessage<::project::Project>(Arena*);
template<> ::project::ProjectHeader* Arena::CreateMaybeMessage<::project::ProjectHeader>(Arena*);
template<> ::project::ProjectNames* Arena::CreateMaybeMessage<::project::ProjectNames>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace project {

// ===================================================================

class Project final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:project.Project) */ {
 public:
  inline Project() : Project(nullptr) {}
  ~Project() override;
  explicit PROTOBUF_CONSTEXPR Project(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Project(const Project& from);
  Project(Project&& from) noexcept
    : Project() {
    *this = ::std::move(from);
  }

  inline Project& operator=(const Project& from) {
    CopyFrom(from);
    return *this;
  }
  inline Project& operator=(Project&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Project& default_instance() {
    return *internal_default_instance();
  }
  static inline const Project* internal_default_instance() {
    return reinterpret_cast<const Project*>(
               &_Project_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Project& a, Project& b) {
    a.Swap(&b);
  }
  inline void Swap(Project* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Project* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Project* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Project>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Project& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Project& from) {
    Project::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Project* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "project.Project";
  }
  protected:
  explicit Project(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTextFieldNumber = 4,
    kIdFieldNumber = 1,
    kNameFieldNumber = 2,
    kAuthorFieldNumber = 3,
    kCreatedtimeFieldNumber = 11,
    kLastmodifiedFieldNumber = 12,
    kVersionFieldNumber = 5,
    kOperationscountFieldNumber = 6,
  };
  // repeated string text = 4;
  int text_size() const;
  private:
  int _internal_text_size() const;
  public:
  void clear_text();
  const std::string& text(int index) const;
  std::string* mutable_text(int index);
  void set_text(int index, const std::string& value);
  void set_text(int index, std::string&& value);
  void set_text(int index, const char* value);
  void set_text(int index, const char* value, size_t size);
  std::string* add_text();
  void add_text(const std::string& value);
  void add_text(std::string&& value);
  void add_text(const char* value);
  void add_text(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& text() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_text();
  private:
  const std::string& _internal_text(int index) const;
  std::string* _internal_add_text();
  public:

  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // optional string author = 3;
  bool has_author() const;
  private:
  bool _internal_has_author() const;
  public:
  void clear_author();
  const std::string& author() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_author(ArgT0&& arg0, ArgT... args);
  std::string* mutable_author();
  PROTOBUF_NODISCARD std::string* release_author();
  void set_allocated_author(std::string* author);
  private:
  const std::string& _internal_author() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_author(const std::string& value);
  std::string* _internal_mutable_author();
  public:

  // string createdtime = 11;
  void clear_createdtime();
  const std::string& createdtime() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_createdtime(ArgT0&& arg0, ArgT... args);
  std::string* mutable_createdtime();
  PROTOBUF_NODISCARD std::string* release_createdtime();
  void set_allocated_createdtime(std::string* createdtime);
  private:
  const std::string& _internal_createdtime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_createdtime(const std::string& value);
  std::string* _internal_mutable_createdtime();
  public:

  // string lastmodified = 12;
  void clear_lastmodified();
  const std::string& lastmodified() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_lastmodified(ArgT0&& arg0, ArgT... args);
  std::string* mutable_lastmodified();
  PROTOBUF_NODISCARD std::string* release_lastmodified();
  void set_allocated_lastmodified(std::string* lastmodified);
  private:
  const std::string& _internal_lastmodified() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_lastmodified(const std::string& value);
  std::string* _internal_mutable_lastmodified();
  public:

  // int32 version = 5;
  void clear_version();
  int32_t version() const;
  void set_version(int32_t value);
  private:
  int32_t _internal_version() const;
  void _internal_set_version(int32_t value);
  public:

  // int32 operationscount = 6;
  void clear_operationscount();
  int32_t operationscount() const;
  void set_operationscount(int32_t value);
  private:
  int32_t _internal_operationscount() const;
  void _internal_set_operationscount(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:project.Project)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> text_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr author_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr createdtime_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lastmodified_;
    int32_t version_;
    int32_t operationscount_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_project_2eproto;
};
// -------------------------------------------------------------------

class ProjectHeader final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:project.ProjectHeader) */ {
 public:
  inline ProjectHeader() : ProjectHeader(nullptr) {}
  ~ProjectHeader() override;
  explicit PROTOBUF_CONSTEXPR ProjectHeader(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProjectHeader(const ProjectHeader& from);
  ProjectHeader(ProjectHeader&& from) noexcept
    : ProjectHeader() {
    *this = ::std::move(from);
  }

  inline ProjectHeader& operator=(const ProjectHeader& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProjectHeader& operator=(ProjectHeader&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProjectHeader& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProjectHeader* internal_default_instance() {
    return reinterpret_cast<const ProjectHeader*>(
               &_ProjectHeader_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ProjectHeader& a, ProjectHeader& b) {
    a.Swap(&b);
  }
  inline void Swap(ProjectHeader* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProjectHeader* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProjectHeader* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProjectHeader>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProjectHeader& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProjectHeader& from) {
    ProjectHeader::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProjectHeader* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "project.ProjectHeader";
  }
  protected:
  explicit ProjectHeader(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kNameFieldNumber = 2,
    kCreationdateFieldNumber = 3,
    kAuthorFieldNumber = 4,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_id();
  PROTOBUF_NODISCARD std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string Creationdate = 3;
  void clear_creationdate();
  const std::string& creationdate() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_creationdate(ArgT0&& arg0, ArgT... args);
  std::string* mutable_creationdate();
  PROTOBUF_NODISCARD std::string* release_creationdate();
  void set_allocated_creationdate(std::string* creationdate);
  private:
  const std::string& _internal_creationdate() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_creationdate(const std::string& value);
  std::string* _internal_mutable_creationdate();
  public:

  // string author = 4;
  void clear_author();
  const std::string& author() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_author(ArgT0&& arg0, ArgT... args);
  std::string* mutable_author();
  PROTOBUF_NODISCARD std::string* release_author();
  void set_allocated_author(std::string* author);
  private:
  const std::string& _internal_author() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_author(const std::string& value);
  std::string* _internal_mutable_author();
  public:

  // @@protoc_insertion_point(class_scope:project.ProjectHeader)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr creationdate_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr author_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_project_2eproto;
};
// -------------------------------------------------------------------

class ProjectNames final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:project.ProjectNames) */ {
 public:
  inline ProjectNames() : ProjectNames(nullptr) {}
  ~ProjectNames() override;
  explicit PROTOBUF_CONSTEXPR ProjectNames(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProjectNames(const ProjectNames& from);
  ProjectNames(ProjectNames&& from) noexcept
    : ProjectNames() {
    *this = ::std::move(from);
  }

  inline ProjectNames& operator=(const ProjectNames& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProjectNames& operator=(ProjectNames&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProjectNames& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProjectNames* internal_default_instance() {
    return reinterpret_cast<const ProjectNames*>(
               &_ProjectNames_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ProjectNames& a, ProjectNames& b) {
    a.Swap(&b);
  }
  inline void Swap(ProjectNames* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProjectNames* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProjectNames* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProjectNames>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProjectNames& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProjectNames& from) {
    ProjectNames::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProjectNames* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "project.ProjectNames";
  }
  protected:
  explicit ProjectNames(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProjectnamesFieldNumber = 1,
    kCounterFieldNumber = 2,
  };
  // repeated .project.ProjectHeader projectnames = 1;
  int projectnames_size() const;
  private:
  int _internal_projectnames_size() const;
  public:
  void clear_projectnames();
  ::project::ProjectHeader* mutable_projectnames(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::project::ProjectHeader >*
      mutable_projectnames();
  private:
  const ::project::ProjectHeader& _internal_projectnames(int index) const;
  ::project::ProjectHeader* _internal_add_projectnames();
  public:
  const ::project::ProjectHeader& projectnames(int index) const;
  ::project::ProjectHeader* add_projectnames();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::project::ProjectHeader >&
      projectnames() const;

  // int32 counter = 2;
  void clear_counter();
  int32_t counter() const;
  void set_counter(int32_t value);
  private:
  int32_t _internal_counter() const;
  void _internal_set_counter(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:project.ProjectNames)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::project::ProjectHeader > projectnames_;
    int32_t counter_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_project_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Project

// string id = 1;
inline void Project::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& Project::id() const {
  // @@protoc_insertion_point(field_get:project.Project.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Project::set_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:project.Project.id)
}
inline std::string* Project::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:project.Project.id)
  return _s;
}
inline const std::string& Project::_internal_id() const {
  return _impl_.id_.Get();
}
inline void Project::_internal_set_id(const std::string& value) {
  
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* Project::_internal_mutable_id() {
  
  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* Project::release_id() {
  // @@protoc_insertion_point(field_release:project.Project.id)
  return _impl_.id_.Release();
}
inline void Project::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:project.Project.id)
}

// string name = 2;
inline void Project::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Project::name() const {
  // @@protoc_insertion_point(field_get:project.Project.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Project::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:project.Project.name)
}
inline std::string* Project::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:project.Project.name)
  return _s;
}
inline const std::string& Project::_internal_name() const {
  return _impl_.name_.Get();
}
inline void Project::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Project::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* Project::release_name() {
  // @@protoc_insertion_point(field_release:project.Project.name)
  return _impl_.name_.Release();
}
inline void Project::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:project.Project.name)
}

// optional string author = 3;
inline bool Project::_internal_has_author() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Project::has_author() const {
  return _internal_has_author();
}
inline void Project::clear_author() {
  _impl_.author_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Project::author() const {
  // @@protoc_insertion_point(field_get:project.Project.author)
  return _internal_author();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Project::set_author(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.author_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:project.Project.author)
}
inline std::string* Project::mutable_author() {
  std::string* _s = _internal_mutable_author();
  // @@protoc_insertion_point(field_mutable:project.Project.author)
  return _s;
}
inline const std::string& Project::_internal_author() const {
  return _impl_.author_.Get();
}
inline void Project::_internal_set_author(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.author_.Set(value, GetArenaForAllocation());
}
inline std::string* Project::_internal_mutable_author() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.author_.Mutable(GetArenaForAllocation());
}
inline std::string* Project::release_author() {
  // @@protoc_insertion_point(field_release:project.Project.author)
  if (!_internal_has_author()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.author_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.author_.IsDefault()) {
    _impl_.author_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Project::set_allocated_author(std::string* author) {
  if (author != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.author_.SetAllocated(author, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.author_.IsDefault()) {
    _impl_.author_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:project.Project.author)
}

// repeated string text = 4;
inline int Project::_internal_text_size() const {
  return _impl_.text_.size();
}
inline int Project::text_size() const {
  return _internal_text_size();
}
inline void Project::clear_text() {
  _impl_.text_.Clear();
}
inline std::string* Project::add_text() {
  std::string* _s = _internal_add_text();
  // @@protoc_insertion_point(field_add_mutable:project.Project.text)
  return _s;
}
inline const std::string& Project::_internal_text(int index) const {
  return _impl_.text_.Get(index);
}
inline const std::string& Project::text(int index) const {
  // @@protoc_insertion_point(field_get:project.Project.text)
  return _internal_text(index);
}
inline std::string* Project::mutable_text(int index) {
  // @@protoc_insertion_point(field_mutable:project.Project.text)
  return _impl_.text_.Mutable(index);
}
inline void Project::set_text(int index, const std::string& value) {
  _impl_.text_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:project.Project.text)
}
inline void Project::set_text(int index, std::string&& value) {
  _impl_.text_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:project.Project.text)
}
inline void Project::set_text(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.text_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:project.Project.text)
}
inline void Project::set_text(int index, const char* value, size_t size) {
  _impl_.text_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:project.Project.text)
}
inline std::string* Project::_internal_add_text() {
  return _impl_.text_.Add();
}
inline void Project::add_text(const std::string& value) {
  _impl_.text_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:project.Project.text)
}
inline void Project::add_text(std::string&& value) {
  _impl_.text_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:project.Project.text)
}
inline void Project::add_text(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.text_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:project.Project.text)
}
inline void Project::add_text(const char* value, size_t size) {
  _impl_.text_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:project.Project.text)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Project::text() const {
  // @@protoc_insertion_point(field_list:project.Project.text)
  return _impl_.text_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Project::mutable_text() {
  // @@protoc_insertion_point(field_mutable_list:project.Project.text)
  return &_impl_.text_;
}

// int32 version = 5;
inline void Project::clear_version() {
  _impl_.version_ = 0;
}
inline int32_t Project::_internal_version() const {
  return _impl_.version_;
}
inline int32_t Project::version() const {
  // @@protoc_insertion_point(field_get:project.Project.version)
  return _internal_version();
}
inline void Project::_internal_set_version(int32_t value) {
  
  _impl_.version_ = value;
}
inline void Project::set_version(int32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:project.Project.version)
}

// int32 operationscount = 6;
inline void Project::clear_operationscount() {
  _impl_.operationscount_ = 0;
}
inline int32_t Project::_internal_operationscount() const {
  return _impl_.operationscount_;
}
inline int32_t Project::operationscount() const {
  // @@protoc_insertion_point(field_get:project.Project.operationscount)
  return _internal_operationscount();
}
inline void Project::_internal_set_operationscount(int32_t value) {
  
  _impl_.operationscount_ = value;
}
inline void Project::set_operationscount(int32_t value) {
  _internal_set_operationscount(value);
  // @@protoc_insertion_point(field_set:project.Project.operationscount)
}

// string createdtime = 11;
inline void Project::clear_createdtime() {
  _impl_.createdtime_.ClearToEmpty();
}
inline const std::string& Project::createdtime() const {
  // @@protoc_insertion_point(field_get:project.Project.createdtime)
  return _internal_createdtime();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Project::set_createdtime(ArgT0&& arg0, ArgT... args) {
 
 _impl_.createdtime_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:project.Project.createdtime)
}
inline std::string* Project::mutable_createdtime() {
  std::string* _s = _internal_mutable_createdtime();
  // @@protoc_insertion_point(field_mutable:project.Project.createdtime)
  return _s;
}
inline const std::string& Project::_internal_createdtime() const {
  return _impl_.createdtime_.Get();
}
inline void Project::_internal_set_createdtime(const std::string& value) {
  
  _impl_.createdtime_.Set(value, GetArenaForAllocation());
}
inline std::string* Project::_internal_mutable_createdtime() {
  
  return _impl_.createdtime_.Mutable(GetArenaForAllocation());
}
inline std::string* Project::release_createdtime() {
  // @@protoc_insertion_point(field_release:project.Project.createdtime)
  return _impl_.createdtime_.Release();
}
inline void Project::set_allocated_createdtime(std::string* createdtime) {
  if (createdtime != nullptr) {
    
  } else {
    
  }
  _impl_.createdtime_.SetAllocated(createdtime, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.createdtime_.IsDefault()) {
    _impl_.createdtime_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:project.Project.createdtime)
}

// string lastmodified = 12;
inline void Project::clear_lastmodified() {
  _impl_.lastmodified_.ClearToEmpty();
}
inline const std::string& Project::lastmodified() const {
  // @@protoc_insertion_point(field_get:project.Project.lastmodified)
  return _internal_lastmodified();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Project::set_lastmodified(ArgT0&& arg0, ArgT... args) {
 
 _impl_.lastmodified_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:project.Project.lastmodified)
}
inline std::string* Project::mutable_lastmodified() {
  std::string* _s = _internal_mutable_lastmodified();
  // @@protoc_insertion_point(field_mutable:project.Project.lastmodified)
  return _s;
}
inline const std::string& Project::_internal_lastmodified() const {
  return _impl_.lastmodified_.Get();
}
inline void Project::_internal_set_lastmodified(const std::string& value) {
  
  _impl_.lastmodified_.Set(value, GetArenaForAllocation());
}
inline std::string* Project::_internal_mutable_lastmodified() {
  
  return _impl_.lastmodified_.Mutable(GetArenaForAllocation());
}
inline std::string* Project::release_lastmodified() {
  // @@protoc_insertion_point(field_release:project.Project.lastmodified)
  return _impl_.lastmodified_.Release();
}
inline void Project::set_allocated_lastmodified(std::string* lastmodified) {
  if (lastmodified != nullptr) {
    
  } else {
    
  }
  _impl_.lastmodified_.SetAllocated(lastmodified, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.lastmodified_.IsDefault()) {
    _impl_.lastmodified_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:project.Project.lastmodified)
}

// -------------------------------------------------------------------

// ProjectHeader

// string id = 1;
inline void ProjectHeader::clear_id() {
  _impl_.id_.ClearToEmpty();
}
inline const std::string& ProjectHeader::id() const {
  // @@protoc_insertion_point(field_get:project.ProjectHeader.id)
  return _internal_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProjectHeader::set_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:project.ProjectHeader.id)
}
inline std::string* ProjectHeader::mutable_id() {
  std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:project.ProjectHeader.id)
  return _s;
}
inline const std::string& ProjectHeader::_internal_id() const {
  return _impl_.id_.Get();
}
inline void ProjectHeader::_internal_set_id(const std::string& value) {
  
  _impl_.id_.Set(value, GetArenaForAllocation());
}
inline std::string* ProjectHeader::_internal_mutable_id() {
  
  return _impl_.id_.Mutable(GetArenaForAllocation());
}
inline std::string* ProjectHeader::release_id() {
  // @@protoc_insertion_point(field_release:project.ProjectHeader.id)
  return _impl_.id_.Release();
}
inline void ProjectHeader::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  _impl_.id_.SetAllocated(id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:project.ProjectHeader.id)
}

// string name = 2;
inline void ProjectHeader::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& ProjectHeader::name() const {
  // @@protoc_insertion_point(field_get:project.ProjectHeader.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProjectHeader::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:project.ProjectHeader.name)
}
inline std::string* ProjectHeader::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:project.ProjectHeader.name)
  return _s;
}
inline const std::string& ProjectHeader::_internal_name() const {
  return _impl_.name_.Get();
}
inline void ProjectHeader::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* ProjectHeader::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* ProjectHeader::release_name() {
  // @@protoc_insertion_point(field_release:project.ProjectHeader.name)
  return _impl_.name_.Release();
}
inline void ProjectHeader::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:project.ProjectHeader.name)
}

// string Creationdate = 3;
inline void ProjectHeader::clear_creationdate() {
  _impl_.creationdate_.ClearToEmpty();
}
inline const std::string& ProjectHeader::creationdate() const {
  // @@protoc_insertion_point(field_get:project.ProjectHeader.Creationdate)
  return _internal_creationdate();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProjectHeader::set_creationdate(ArgT0&& arg0, ArgT... args) {
 
 _impl_.creationdate_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:project.ProjectHeader.Creationdate)
}
inline std::string* ProjectHeader::mutable_creationdate() {
  std::string* _s = _internal_mutable_creationdate();
  // @@protoc_insertion_point(field_mutable:project.ProjectHeader.Creationdate)
  return _s;
}
inline const std::string& ProjectHeader::_internal_creationdate() const {
  return _impl_.creationdate_.Get();
}
inline void ProjectHeader::_internal_set_creationdate(const std::string& value) {
  
  _impl_.creationdate_.Set(value, GetArenaForAllocation());
}
inline std::string* ProjectHeader::_internal_mutable_creationdate() {
  
  return _impl_.creationdate_.Mutable(GetArenaForAllocation());
}
inline std::string* ProjectHeader::release_creationdate() {
  // @@protoc_insertion_point(field_release:project.ProjectHeader.Creationdate)
  return _impl_.creationdate_.Release();
}
inline void ProjectHeader::set_allocated_creationdate(std::string* creationdate) {
  if (creationdate != nullptr) {
    
  } else {
    
  }
  _impl_.creationdate_.SetAllocated(creationdate, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.creationdate_.IsDefault()) {
    _impl_.creationdate_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:project.ProjectHeader.Creationdate)
}

// string author = 4;
inline void ProjectHeader::clear_author() {
  _impl_.author_.ClearToEmpty();
}
inline const std::string& ProjectHeader::author() const {
  // @@protoc_insertion_point(field_get:project.ProjectHeader.author)
  return _internal_author();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProjectHeader::set_author(ArgT0&& arg0, ArgT... args) {
 
 _impl_.author_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:project.ProjectHeader.author)
}
inline std::string* ProjectHeader::mutable_author() {
  std::string* _s = _internal_mutable_author();
  // @@protoc_insertion_point(field_mutable:project.ProjectHeader.author)
  return _s;
}
inline const std::string& ProjectHeader::_internal_author() const {
  return _impl_.author_.Get();
}
inline void ProjectHeader::_internal_set_author(const std::string& value) {
  
  _impl_.author_.Set(value, GetArenaForAllocation());
}
inline std::string* ProjectHeader::_internal_mutable_author() {
  
  return _impl_.author_.Mutable(GetArenaForAllocation());
}
inline std::string* ProjectHeader::release_author() {
  // @@protoc_insertion_point(field_release:project.ProjectHeader.author)
  return _impl_.author_.Release();
}
inline void ProjectHeader::set_allocated_author(std::string* author) {
  if (author != nullptr) {
    
  } else {
    
  }
  _impl_.author_.SetAllocated(author, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.author_.IsDefault()) {
    _impl_.author_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:project.ProjectHeader.author)
}

// -------------------------------------------------------------------

// ProjectNames

// repeated .project.ProjectHeader projectnames = 1;
inline int ProjectNames::_internal_projectnames_size() const {
  return _impl_.projectnames_.size();
}
inline int ProjectNames::projectnames_size() const {
  return _internal_projectnames_size();
}
inline void ProjectNames::clear_projectnames() {
  _impl_.projectnames_.Clear();
}
inline ::project::ProjectHeader* ProjectNames::mutable_projectnames(int index) {
  // @@protoc_insertion_point(field_mutable:project.ProjectNames.projectnames)
  return _impl_.projectnames_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::project::ProjectHeader >*
ProjectNames::mutable_projectnames() {
  // @@protoc_insertion_point(field_mutable_list:project.ProjectNames.projectnames)
  return &_impl_.projectnames_;
}
inline const ::project::ProjectHeader& ProjectNames::_internal_projectnames(int index) const {
  return _impl_.projectnames_.Get(index);
}
inline const ::project::ProjectHeader& ProjectNames::projectnames(int index) const {
  // @@protoc_insertion_point(field_get:project.ProjectNames.projectnames)
  return _internal_projectnames(index);
}
inline ::project::ProjectHeader* ProjectNames::_internal_add_projectnames() {
  return _impl_.projectnames_.Add();
}
inline ::project::ProjectHeader* ProjectNames::add_projectnames() {
  ::project::ProjectHeader* _add = _internal_add_projectnames();
  // @@protoc_insertion_point(field_add:project.ProjectNames.projectnames)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::project::ProjectHeader >&
ProjectNames::projectnames() const {
  // @@protoc_insertion_point(field_list:project.ProjectNames.projectnames)
  return _impl_.projectnames_;
}

// int32 counter = 2;
inline void ProjectNames::clear_counter() {
  _impl_.counter_ = 0;
}
inline int32_t ProjectNames::_internal_counter() const {
  return _impl_.counter_;
}
inline int32_t ProjectNames::counter() const {
  // @@protoc_insertion_point(field_get:project.ProjectNames.counter)
  return _internal_counter();
}
inline void ProjectNames::_internal_set_counter(int32_t value) {
  
  _impl_.counter_ = value;
}
inline void ProjectNames::set_counter(int32_t value) {
  _internal_set_counter(value);
  // @@protoc_insertion_point(field_set:project.ProjectNames.counter)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace project

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_project_2eproto
